name: movie list CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Configuration de Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Installation des dépendances
        run: npm install

      - name: Installation de firebase-tools
        run: npm install -g firebase-tools

      - name: Build
        run: npm run build

      - name: Archivage du Build
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist

  deploy:
    name: Déploiement
    needs: dist
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Déploiement vers Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}